name: navigation
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  core:
    path: ../core
  core_ui:
    path: ../core_ui
  home_page:
    path: ../features/home_page

  auto_route: ^9.3.0+1

dev_dependencies:
  flutter_lints: ^3.0.1
  auto_route_generator: ^9.3.1
  build_runner: ^2.4.8